---
- name: Verify
  hosts: all
  become: true
  gather_facts: false


  tasks:
    - name: Check if ports are open
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 2
      loop:
        - "8080"
